Add IPv6 support
errbotio/rocket pull request #1
Opened 2017-05-15 16:04 UTC by globin

Adds support to listen on IPv6:
```
!plugin config Webserver {'HOST': '::', 'PORT': 3141}
```

Also works for IPv4 due to `net.ipv6.bindv6only` being false by default.

2017-10-26 09:40 UTC, globin commented
ping @gbin

2017-10-26 10:18 UTC, gbin-argo commented
Thanks

2017-10-26 10:22 UTC, gbin-argo requested changes

2017-10-26 10:22 UTC, gbin-argo commented on rocket/listener.py
> +                listener = None
Shouldn't we at least log a message or the exception?

2017-10-26 10:22 UTC, gbin-argo commented on rocket/listener.py
> +            self.err_log.error("failed to get socket.")
Because this won't leave any specific explanation

2017-10-29 18:39 UTC, gbin commented
Just logging the exception correctly and I'll merge this one.

2017-11-02 11:08 UTC, globin commented
Done

2017-11-13 16:20 UTC, gbin approved these changes

2017-11-13 16:20 UTC, merged